"""README badges equal what `scripts.badges` derives from `.badges/measurements.json`.

`infra`: port's own bookkeeping.
"""

import json
import re
from pathlib import Path

import pytest

from scripts.badges import BADGES, MEASUREMENTS, UNMEASURED, badges, write
from tests import ROOT

README = ROOT / "README.md"

ENDPOINT = re.compile(
    r"!\[[^\]]*\]\(https://img\.shields\.io/endpoint\?url=[^)]*?/\.badges/([a-z-]+)\.json\)"
)
"""Each badge the README renders, by file name."""


@pytest.mark.infra
def test_every_badge_file_is_what_the_measurements_produce() -> None:
    """Each committed badge equals the generator's payload, colour included."""
    for badge in badges():
        path = BADGES / f"{badge.name}.json"

        assert path.exists(), f"{path.name} is missing; run `python -m scripts.badges`"

        assert json.loads(path.read_text()) == badge.payload(), (
            f"{path.name} is stale; run `python -m scripts.badges`"
        )


@pytest.mark.infra
def test_no_badge_file_outlives_the_generator() -> None:
    """No badge file exists that the generator does not make."""
    orphans = {
        path.name for path in BADGES.glob("*.json") if path.name != MEASUREMENTS.name
    } - {f"{badge.name}.json" for badge in badges()}

    assert not orphans, f"{sorted(orphans)} are generated by nothing; delete them"


@pytest.mark.infra
def test_the_readme_renders_every_badge_and_no_others() -> None:
    """The README renders exactly the generated badges."""
    rendered = set(ENDPOINT.findall(README.read_text()))
    generated = {badge.name for badge in badges()}

    assert rendered == generated, (
        f"README renders {sorted(rendered)}, the generator makes {sorted(generated)}"
    )


@pytest.mark.infra
def test_every_measurement_carries_the_conditions_that_decided_it() -> None:
    """Every recorded measurement states the conditions and its ratio matches its counts."""
    recorded = json.loads(MEASUREMENTS.read_text())

    for name, guard in recorded["coverage"].items():
        for key in ("label", "percent", "floor", "selection", "denominator", "commit"):
            assert key in guard, f"coverage guard {name} does not state {key}"

        if guard["percent"] is None:
            assert guard.get("note"), (
                f"coverage guard {name} is unmeasured and does not say why"
            )

    patched = recorded.get("patched")

    if patched is not None:
        for key in ("percent", "patched_lines", "executed_lines", "instance", "commit"):
            assert key in patched, f"the patched share does not state {key}"

        assert patched["patched_lines"] <= patched["executed_lines"]
        assert patched["percent"] == pytest.approx(
            100.0 * patched["patched_lines"] / patched["executed_lines"], abs=0.005
        ), "the percent is not the recorded counts' ratio"

    recovery = recorded.get("recovery")

    if recovery is not None:
        for key in ("instance", "configuration", "commit", "arms"):
            assert key in recovery, f"the recovery measurement does not state {key}"

        for arm, values in recovery["arms"].items():
            assert {"ari", "ari_integer", "copy_ari", "flags"} <= set(values), (
                f"recovery arm {arm} does not state its flags and its indices"
            )

    speed = recorded.get("speed")

    if speed is not None:
        for key in (
            "sample",
            "commit",
            "calicost_seconds",
            "port_seconds",
            "port_cores",
            "assumption",
            "ratio",
        ):
            assert key in speed, f"the speed measurement does not state {key}"

        assert speed["ratio"] == pytest.approx(
            speed["calicost_seconds"] / speed["port_seconds"], rel=1e-3
        ), "the ratio is not the recorded walls' ratio"

    run = recorded["whole_run"]

    for key in ("instance", "commit", "arms"):
        assert key in run, f"the whole-run measurement does not state {key}"

    if run.get("ratio") is None:
        assert run.get("note"), "a comparison with no ratio must say what happened"
    else:
        assert set(run["ratio"]) == {"runtime", "memory"}

        # NB presence alone passes a null; a ratio must name its instance and two
        #    completed arms, since CI cannot re-measure a whole run
        assert run["instance"], "a ratio must name the instance it was read at"

        assert len(run["arms"]) == 2, (
            f"a ratio is two arms; {len(run['arms'])} recorded"
        )

        assert all(arm["returncode"] == 0 for arm in run["arms"]), (
            "a ratio from an arm that did not complete is not a ratio"
        )


@pytest.mark.infra
def test_the_generator_is_idempotent(tmp_path: Path) -> None:
    """Two generator runs write the same bytes."""
    before = {path.name: path.read_bytes() for path in write()}
    after = {path.name: path.read_bytes() for path in write()}

    assert before == after


@pytest.mark.infra
def test_a_ratio_is_never_rendered_without_its_instance() -> None:
    """A rendered ratio requires the `instance` badge to be measured."""
    recorded = json.loads(MEASUREMENTS.read_text())

    if recorded["whole_run"].get("ratio") is None:
        pytest.skip("no ratio was produced; the badges carry the reason instead")

    rendered = {badge.name: badge for badge in badges()}
    instance = rendered["instance"]

    assert instance.message != UNMEASURED, (
        "a ratio is rendered but `instance` reads unmeasured, so the numbers "
        "name no size"
    )

    for name, badge in rendered.items():
        if name.startswith("run-"):
            assert badge.message.endswith("X"), f"{name} is not in ratio units"
