"""The port-forward table: each swap row, the `cnaster` function it replaces,
what it depends on, and the tests that pin it (T- #617 WP11, goal 3).

`python -m scripts.port_forward` writes `docs/port-forward.md` from
`port.pipeline`'s tables, in the order a future series against a `cnaster`
copy would apply them: standalone rows first, then preprocessing, the fit
chain and clone assignment, with the shift before the extensions that sit on
it. It opens no pull request against `cnaster`; the `port-forward` rule checks
that the committed table is what this writes.
"""

from __future__ import annotations

import ast
import inspect
import sys
from importlib import import_module
from pathlib import Path
from typing import Any

from port.extensions.repository import ROOT
from port.pipeline import OUTSIDE_TABLES

from tests.source_graph import edges, tables

OUT = ROOT / "docs" / "port-forward.md"

STAGES: tuple[tuple[str, frozenset[str]], ...] = (
    (
        "standalone",
        frozenset(
            {
                "cnaster.utils",
                "cnaster.plot_genomic",
                "cnaster.plotting",
                "cnaster.plot_copy_number_profile",
            }
        ),
    ),
    (
        "preprocessing",
        frozenset(
            {
                "cnaster.io",
                "cnaster.he",
                "cnaster.reference",
                "cnaster.omics",
                "cnaster.recomb",
                "cnaster.normal_spot",
                "cnaster.spatial",
                "cnaster.pseudobulk",
            }
        ),
    ),
    (
        "fit chain",
        frozenset(
            {"cnaster.count_encoder", "cnaster.hmm_nophasing", "cnaster.hmm_phased"}
        ),
    ),
    ("clone assignment", frozenset({"cnaster.hmrf", "cnaster.integer_copy"})),
)
"""Each stage and the `cnaster` modules whose rows it holds, in series order."""

TABLE_ORDER = (
    "SWAPS",
    "SHIFT_SWAPS",
    "LOG_SPACE_SWAPS",
    "REFINEMENT_SWAPS",
    "COPY_SWAPS",
    "FIGURE_SWAPS",
    "PLOT_OFF_SWAPS",
)
"""Within a stage: the bitwise table, then the shift, then what sits on it."""


def _stage(module: str) -> int:
    for index, (_, members) in enumerate(STAGES):
        if module in members:
            return index
    msg = f"{module} is in no stage of STAGES"
    raise LookupError(msg)


def _upstream(module: str, name: str) -> str:
    """`cnaster/<file>:<line> <name>`, where `cnaster` defines it."""
    target: Any = getattr(import_module(module), name)
    target = getattr(target, "py_func", target)
    parts = Path(inspect.getsourcefile(target) or "").parts
    where = "/".join(parts[len(parts) - 1 - parts[::-1].index("cnaster") :])
    line = inspect.getsourcelines(target)[1]
    return f"`{where}:{line}` `{name}`"


def _pinning() -> dict[tuple[str, str], list[str]]:
    """`(module, name)` -> the test files that import it by name."""
    found: dict[tuple[str, str], list[str]] = {}

    # NB `glob`, not `rglob`: a `tests/sandbox/` test pins no live row (#851)
    for path in sorted((ROOT / "tests").glob("test_*.py")):
        for node in ast.walk(ast.parse(path.read_text())):
            if isinstance(node, ast.ImportFrom) and node.module:
                for alias in node.names:
                    found.setdefault((node.module, alias.name), []).append(path.name)

    return found


def rows() -> list[tuple[str, ...]]:
    """One tuple per row: order, stage, table, upstream, replacement, dependencies, tests."""
    pinned = _pinning()
    keyed = []

    for table, swaps in tables().items():
        for swap in swaps:
            base, _, attribute = swap.replacement.partition(":")
            defined = getattr(import_module(base), attribute).__module__
            tests = sorted(
                set(pinned.get((base, attribute), []))
                | set(pinned.get((defined, attribute), []))
            )
            depends = sorted(edges(defined)) if defined in sys.modules else []
            keyed.append(
                (
                    (_stage(swap.module), TABLE_ORDER.index(table), swap.ticket),
                    (
                        STAGES[_stage(swap.module)][0],
                        table,
                        _upstream(swap.module, swap.name),
                        f"`{swap.replacement}` (#{swap.ticket})",
                        ", ".join(f"`{d}`" for d in depends) or "--",
                        ", ".join(f"`{t}`" for t in tests) or "**none**",
                    ),
                )
            )

    keyed.sort(key=lambda item: item[0])
    return [(str(i + 1), *row) for i, (_, row) in enumerate(keyed)]


def render() -> str:
    lines = [
        "# Port-forward table",
        "",
        "Generated by `python -m scripts.port_forward` from `port.pipeline`'s swap",
        "tables (T- #617 WP11); do not edit by hand. Each row is one `cnaster`",
        "function, in the order a series against a `cnaster` copy would apply",
        "it: standalone, preprocessing, fit chain, clone assignment, the shift",
        "before what sits on it. **Tests** are the test files that import the",
        "replacement by name; **none** is a row with no direct test.",
        "",
        "| # | stage | table | `cnaster` | replacement | depends on | tests |",
        "| ---: | --- | --- | --- | --- | --- | --- |",
    ]
    lines += ["| " + " | ".join(row) + " |" for row in rows()]
    lines += [
        "",
        "## Outside the tables",
        "",
        "Replaced other than by a swap row (`port.pipeline.OUTSIDE_TABLES`, #749 WP8).",
        "",
        "| `cnaster` | replacement | how |",
        "| --- | --- | --- |",
    ]
    lines += [
        f"| `{upstream}` | `{replacement}` | {how} |"
        for upstream, replacement, how in OUTSIDE_TABLES
    ]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    OUT.write_text(render())
    print(f"wrote {OUT.relative_to(ROOT)}: {len(rows())} rows")
